const bdColeccion = [
  // NATAHA (ids 1â€“25)
  { id: 1,  serie: "Natacha",      titulo: "Natacha hÃ´tesse de l'air",             autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 2,  serie: "Natacha",      titulo: "Natacha et le Maharadjah",             autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 3,  serie: "Natacha",      titulo: "La MÃ©moire de mÃ©tal",                  autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 4,  serie: "Natacha",      titulo: "Un trÃ´ne pour Natacha",                autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 5,  serie: "Natacha",      titulo: "Double vol",                           autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 6,  serie: "Natacha",      titulo: "Un brin de panique",                   autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 7,  serie: "Natacha",      titulo: "L'Ange blond",                         autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 8,  serie: "Natacha",      titulo: "Les Machines incertaines",             autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 9,  serie: "Natacha",      titulo: "L'Ile d'outre-monde",                  autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 10, serie: "Natacha",      titulo: "Cauchemirage",                         autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 11, serie: "Natacha",      titulo: "Le Grand pari",                        autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: true  },
  { id: 12, serie: "Natacha",      titulo: "La Ceinture de Cherchemidi",           autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 13, serie: "Natacha",      titulo: "Kerguelen",                            autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 14, serie: "Natacha",      titulo: "Les Culottes de fer",                  autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 15, serie: "Natacha",      titulo: "Natacha et les petits anges",          autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 16, serie: "Natacha",      titulo: "Au septiÃ¨me ciel",                     autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 17, serie: "Natacha",      titulo: "La Veuve noire",                       autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 18, serie: "Natacha",      titulo: "Natacha et les dinosaures",            autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 19, serie: "Natacha",      titulo: "La Mer de rochers",                    autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 20, serie: "Natacha",      titulo: "Atoll 66",                             autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 21, serie: "Natacha",      titulo: "Le Regard du passÃ©",                   autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 22, serie: "Natacha",      titulo: "L'Ã‰pervier bleu",                      autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 23, serie: "Natacha",      titulo: "Sur les traces de l'Ã‰pervier bleu",    autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 24, serie: "Natacha",      titulo: "Chanson d'avril",                      autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },
  { id: 25, serie: "Natacha",      titulo: "Le Grand pari",                        autor: "WalthÃ©ry",                                            editorial: "Dupuis", estado: "", tieneslu: false },

  // YOKO TSUNO (ids 26â€“56)
  { id: 26, serie: "Yoko Tsuno",   titulo: "Le Trio de l'Ã©trange",                 autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 27, serie: "Yoko Tsuno",   titulo: "L'Orgue du diable",                    autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 28, serie: "Yoko Tsuno",   titulo: "La Forge de Vulcain",                  autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 29, serie: "Yoko Tsuno",   titulo: "Aventures Ã©lectroniques",              autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 30, serie: "Yoko Tsuno",   titulo: "Message pour l'Ã©ternitÃ©",              autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 31, serie: "Yoko Tsuno",   titulo: "Les Trois soleils de VinÃ©a",           autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 32, serie: "Yoko Tsuno",   titulo: "La FrontiÃ¨re de la vie",               autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 33, serie: "Yoko Tsuno",   titulo: "Les Titans",                           autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 34, serie: "Yoko Tsuno",   titulo: "La Fille du vent",                     autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 35, serie: "Yoko Tsuno",   titulo: "La LumiÃ¨re d'Ixo",                     autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 36, serie: "Yoko Tsuno",   titulo: "La Spirale du temps",                  autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 37, serie: "Yoko Tsuno",   titulo: "La Proie et l'ombre",                  autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 38, serie: "Yoko Tsuno",   titulo: "Les Archanges de VinÃ©a",               autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 39, serie: "Yoko Tsuno",   titulo: "Le Feu de Wotan",                      autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 40, serie: "Yoko Tsuno",   titulo: "Le Canon de Kra",                      autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 41, serie: "Yoko Tsuno",   titulo: "Le Dragon de Hong Kong",               autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 42, serie: "Yoko Tsuno",   titulo: "Le Matin du monde",                    autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 43, serie: "Yoko Tsuno",   titulo: "Les ExilÃ©s de Kifa",                   autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 44, serie: "Yoko Tsuno",   titulo: "L'Or du Rhin",                         autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 45, serie: "Yoko Tsuno",   titulo: "L'Astrologue de Bruges",               autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 46, serie: "Yoko Tsuno",   titulo: "La Porte des Ã¢mes",                    autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 47, serie: "Yoko Tsuno",   titulo: "La Jonque cÃ©leste",                    autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 48, serie: "Yoko Tsuno",   titulo: "La Pagode des brumes",                 autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 49, serie: "Yoko Tsuno",   titulo: "Le SeptiÃ¨me Code",                     autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 50, serie: "Yoko Tsuno",   titulo: "La servante de Lucifer",               autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 51, serie: "Yoko Tsuno",   titulo: "Le malÃ©fice de l'amÃ©thyste",          autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 52, serie: "Yoko Tsuno",   titulo: "Le secret de KhÃ¢ny",                   autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 53, serie: "Yoko Tsuno",   titulo: "Le temple des immortels",              autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 54, serie: "Yoko Tsuno",   titulo: "Anges et faucons",                     autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 55, serie: "Yoko Tsuno",   titulo: "Les gÃ©meaux de Saturne",               autor: "Roger Leloup", estado: "", tieneslu: false },
  { id: 56, serie: "Yoko Tsuno",   titulo: "L'aigle des Highlands",                autor: "Roger Leloup", estado: "", tieneslu: false },

  // BLAKE & MORTIMER (ids 57â€“68)
  { id: 57, serie: "Blake & Mortimer", titulo: "Le Secret de l'Espadon (Tome 1)",   autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 58, serie: "Blake & Mortimer", titulo: "Le Secret de l'Espadon (Tome 2)",   autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 59, serie: "Blake & Mortimer", titulo: "Le Secret de l'Espadon (Tome 3)",   autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 60, serie: "Blake & Mortimer", titulo: "Le MystÃ¨re de la Grande Pyramide (Tome 1)", autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 61, serie: "Blake & Mortimer", titulo: "Le MystÃ¨re de la Grande Pyramide (Tome 2)", autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 62, serie: "Blake & Mortimer", titulo: "La Marque Jaune",                    autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 63, serie: "Blake & Mortimer", titulo: "L'Ã‰nigme de l'Atlantide",           autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 64, serie: "Blake & Mortimer", titulo: "S.O.S. MÃ©tÃ©ores",                    autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 65, serie: "Blake & Mortimer", titulo: "Le PiÃ¨ge diabolique",                autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 66, serie: "Blake & Mortimer", titulo: "L'Affaire du Collier",               autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 67, serie: "Blake & Mortimer", titulo: "Les Trois Formules du Professeur Sato (Tome 1)", autor: "E.P. Jacobs", estado: "", tieneslu: false },
  { id: 68, serie: "Blake & Mortimer", titulo: "Les Trois Formules du Professeur Sato (Tome 2)", autor: "E.P. Jacobs", estado: "", tieneslu: false },

  // BLACKSAD (ids 69â€“75)
  { id: 69, serie: "Blacksad",       titulo: "Un Lugar entre las Sombras",           autor: "Juan DÃ­az Canales / Juanjo Guarnido", estado: "", tieneslu: false },
  { id: 70, serie: "Blacksad",       titulo: "Arctic Nation",                        autor: "Juan DÃ­az Canales / Juanjo Guarnido", estado: "", tieneslu: false },
  { id: 71, serie: "Blacksad",       titulo: "Alma Roja",                            autor: "Juan DÃ­az Canales / Juanjo Guarnido", estado: "", tieneslu: false },
  { id: 72, serie: "Blacksad",       titulo: "El Infierno, el Silencio",            autor: "Juan DÃ­az Canales / Juanjo Guarnido", estado: "", tieneslu: false },
  { id: 73, serie: "Blacksad",       titulo: "Amarillo",                             autor: "Juan DÃ­az Canales / Juanjo Guarnido", estado: "", tieneslu: false },
  { id: 74, serie: "Blacksad",       titulo: "Todo CaerÃ¡. Primera Parte",           autor: "Juan DÃ­az Canales / Juanjo Guarnido", estado: "", tieneslu: false },
  { id: 75, serie: "Blacksad",       titulo: "Todo CaerÃ¡. Segunda Parte",           autor: "Juan DÃ­az Canales / Juanjo Guarnido", estado: "", tieneslu: false }
];